// This file is regenerated by `pnpm payload generate:importmap`. The
// initial export below is a stub so the app compiles before the first
// generation; payload will rewrite it on first run / when richtext
// features are added.
/** @type import('payload').ImportMap */
export const importMap = {}
