import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { colors, darkOverrides } from '../src/tokens/colors.ts'
import { layout } from '../src/tokens/layout.ts'
import { radii } from '../src/tokens/radii.ts'
import { spacing } from '../src/tokens/spacing.ts'
import { typography } from '../src/tokens/typography.ts'

const __dirname = dirname(fileURLToPath(import.meta.url))
const outputPath = resolve(__dirname, '../src/styles/tokens.css')

/** Turns `color.brand.primaryHover` into `--color-brand-primary-hover`. */
function tokenToVariable(name: string): string {
  const kebab = name.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase()
  return `--${kebab.replace(/\./g, '-')}`
}

function section(title: string, entries: Array<readonly [string, string]>): string {
  const rules = entries.map(([name, value]) => `  ${tokenToVariable(name)}: ${value};`).join('\n')
  return `  /* ${title} */\n${rules}`
}

const light = [
  section('Colors', Object.entries(colors)),
  section('Typography', Object.entries(typography)),
  section('Spacing', Object.entries(spacing)),
  section('Radii', Object.entries(radii)),
  section('Layout & Containers', Object.entries(layout)),
].join('\n\n')

const dark = Object.entries(darkOverrides)
  .map(([name, value]) => `    ${tokenToVariable(name)}: ${value};`)
  .join('\n')

const banner = '/* Auto-generated by scripts/build-tokens-css.ts. Do not edit by hand. */'

const output = `${banner}\n\n:root {\n${light}\n}\n\n@media (prefers-color-scheme: dark) {\n  :root {\n${dark}\n  }\n}\n`

await mkdir(dirname(outputPath), { recursive: true })
await writeFile(outputPath, output, 'utf8')

console.log(`Wrote ${outputPath}`)
