export default function HomePage() {
  return (
    <main style={{ padding: '4rem 2rem', maxWidth: 720, margin: '0 auto' }}>
      <h1>{{projectName}}</h1>
      <p>
        This is a placeholder home page generated by{' '}
        <code>@forumone/create-throughline</code>.
      </p>
      <p>
        Visit{' '}
        <a href="/admin">
          <code>/admin</code>
        </a>{' '}
        to set up your first user, then replace this page with your real frontend.
      </p>
    </main>
  )
}
